### ISSUE TITLE
[BUG] Upgrading Azure-Communication-Calling from 2.4.0 to 2.11.0 causing a run time error

### ISSUE THREAD

**Issue by franciscerio** [Azure/azure-sdk-for-android#1747]
**Describe the bug**
After I updated our azure-communication-calling 2.4.0 to 2.11.0, I always encountered this issue.

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~tXVLgRgp34eEClMcw7o9fg==/com.app-41VBh9_g0OTEeBMgQoyVfg==/base.apk!/lib/arm64-v8a/libskypert.so"...
    at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
    at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
    at java.lang.System.loadLibrary(System.java:1661)
    at com.azure.android.communication.calling.CallClient.loadNativeLibraries(CallClient.java:404)
    at com.azure.android.communication.calling.CallClient.<clinit>(CallClient.java:413)

***Exception or Stack Trace***
```
FATAL EXCEPTION: main
Process: com.sample.app, PID: 22171
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~tXVLgRgp34eEClMcw7o9fg==/com.sample.app.preprod-41VBh9_g0OTEeBMgQoyVfg==/base.apk!/lib/arm64-v8a/libskypert.so"...
    at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
    at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
    at java.lang.System.loadLibrary(System.java:1661)
    at com.azure.android.communication.calling.CallClient.loadNativeLibraries(CallClient.java:404)
    at com.azure.android.communication.calling.CallClient.<clinit>(CallClient.java:413)
    at com.sample.app.common.communication.engine.AzureCallEngine.setup(AzureCallEngine.kt:89)
    at com.sample.app.ui.communication.call.ConsultationCallActivity.displayAppointmentDetails(ConsultationCallActivity.kt:481)
    at com.sample.app.ui.communication.call.ConsultationCallActivity.access$displayAppointmentDetails(ConsultationCallActivity.kt:55)
    at com.sample.app.ui.communication.call.ConsultationCallActivity$setupObserver$1$1.emit(ConsultationCallActivity.kt:206)
    at com.sample.app.ui.communication.call.ConsultationCallActivity$setupObserver$1$1.emit(ConsultationCallActivity.kt:203)
    at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:382)
    at kotlinx.coroutines.flow.SharedFlowImpl$collect$1.invokeSuspend(Unknown Source:15)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:235)
    at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:191)
    at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:163)
    at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
    at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
    at kotlinx.coroutines.flow.SharedFlowImpl.emitSuspend(SharedFlow.kt:503)
    at kotlinx.coroutines.flow.SharedFlowImpl.emit$suspendImpl(SharedFlow.kt:405)
    at kotlinx.coroutines.flow.SharedFlowImpl.emit(Unknown Source:0)
    at com.sample.app.ui.communication.call.ConsultationCallViewModel$getAppointmentDetails$1.invokeSuspend(ConsultationCallViewModel.kt:36)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at android.os.Handler.handleCallback(Handler.java:958)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loopOnce(Looper.java:230)
    at android.os.Looper.loop(Looper.java:319)
    at android.app.ActivityThread.main(ActivityThread.java:8919)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
    Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f869684, Dispatchers.Main.immediate]

```

**To Reproduce**
Update dependency

***Code Snippet***
from
```
implementation 'com.azure.android:azure-communication-calling:2.4.0'
implementation 'com.azure.android:azure-communication-common:1.1.0'
```

to
```
implementation 'com.azure.android:azure-communication-calling:2.11.0'
implementation 'com.azure.android:azure-communication-common:1.2.1'
```
    

**Expected behavior**
Expected to run without runtime error

**Screenshots**
Sorry I can't, it's in production

**Setup (please complete the following information):**
 - OS: MacOS Monterey 12.5
 - IDE : Android Studio Ladybug | 2024.2.1 Patch 2
 - Version of the Library used : 
com.azure.android:azure-communication-calling:2.4.0
com.azure.android:azure-communication-common:1.1.0

**Additional context**
Tried to do some version downgrade but I encountered a lot of issues aside from UnsatisfiedLinkError

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by raosanat** [comment]
Hi @franciscerio this indeed seems like an issue in our SDK. I tried to reproduce the issue with our public samples here. Can you please try the same and let us know if you see the same issue?

https://github.com/Azure-Samples/communication-services-android-quickstarts/tree/main/Add%20Voice%20Calling
or
https://github.com/Azure-Samples/communication-services-android-quickstarts/tree/main/Add-Chat-Calling
