### ISSUE TITLE
app crashes on init of AzureData; Unable to invoke no-args constructor for class com.azure.data.model.service.ResourceLocation

### ISSUE THREAD

**Issue by SogoGolf** [Azure/azure-sdk-for-android#250]
### Environment
- Android version multiple in range from 6.0+:
- Azure.Android SDK: 
- Azure.Android SDK version: 0.4.0

### Bug Summary
2020-07-01 15:30:28.500 16055-16068/? E/zygote64: Failed sending reply to debugger: Broken pipe
2020-07-01 15:30:40.584 16055-16187/sogo.android.sogogolf E/AndroidRuntime: FATAL EXCEPTION: pool-10-thread-1
    Process: sogo.android.sogogolf, PID: 16055
    java.lang.RuntimeException: Unable to invoke no-args constructor for class com.azure.data.model.service.ResourceLocation. Registering an InstanceCreator with Gson for this type may fix this problem.
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:228)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.azure.data.util.json.ResourceWriteOperationAdapter.deserializeDetails(ResourceWriteOperationAdapter.kt:93)
        at com.azure.data.util.json.ResourceWriteOperationAdapter.deserialize(ResourceWriteOperationAdapter.kt:37)
        at com.azure.data.util.json.ResourceWriteOperationAdapter.deserialize(ResourceWriteOperationAdapter.kt:15)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at com.azure.data.service.ResourceWriteOperationQueue$load$$inlined$safeExecute$lambda$1.run(ResourceWriteOperationQueue.kt:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.UnsupportedOperationException: Abstract class can't be instantiated! Class name: com.azure.data.model.service.ResourceLocation
        at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:120)
        at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:225)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) 
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) 
        at com.google.gson.Gson.fromJson(Gson.java:927) 
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at com.azure.data.util.json.ResourceWriteOperationAdapter.deserializeDetails(ResourceWriteOperationAdapter.kt:93) 
        at com.azure.data.util.json.ResourceWriteOperationAdapter.deserialize(ResourceWriteOperationAdapter.kt:37) 
        at com.azure.data.util.json.ResourceWriteOperationAdapter.deserialize(ResourceWriteOperationAdapter.kt:15) 
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) 
        at com.google.gson.Gson.fromJson(Gson.java:927) 
        at com.google.gson.Gson.fromJson(Gson.java:892) 
        at com.google.gson.Gson.fromJson(Gson.java:841) 
        at com.google.gson.Gson.fromJson(Gson.java:813) 
        at com.azure.data.service.ResourceWriteOperationQueue$load$$inlined$safeExecute$lambda$1.run(ResourceWriteOperationQueue.kt:133) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 

### Steps to Reproduce
Thats a tough one unf. It seems that somehow AzureData gets into a state where it will no longer initialise. When that happens, the app will crash at the very first call to init AzureData, ie.

```AzureData.configure(applicationContext, COSMOS_ACCOUNT_NAME, COSMOS_MASTER_KEY, PermissionMode.All /* or PermissionMode.Read */)```

### Expected Behavior
doesnt crash app

### Actual Behavior
crashes app 

Really appreciate if someone can look into this as its affecting multiple of our Android users

**Comment by SogoGolf** [comment]
hey @NateRickard hope your well ! Did you have any sort of eta on this bug fix ? It's pretty urgent from our side. Even if in the interim there is a workaround. Thanks for the help on this.

**Comment by SogoGolf** [comment]
hi folks any update on this one?

**Comment by bsiegel** [comment]
Hey @SogoGolf, just doing some wild guessing here. Based on your repro steps, you mentioned that this can occur as soon as you first configure AzureData, before you even execute any operations. To me, this points to a possibility that you are using the offline data feature of the library, and the local data store has been corrupted. Are you using offline data? If so, can you try disabling it?:

```kt
AzureData.offlineDataEnabled = false
```

If you require the offline data feature, you could try catching the exception and deleting the cache directory when this situation occurs. The `ResourceCache` class has a convenient `purge()` method for this, but unfortunately the class is internal. But I believe the following should achieve the same result:

```kt
try {
    AzureData.configure(applicationContext, COSMOS_ACCOUNT_NAME, COSMOS_MASTER_KEY, PermissionMode.All /* or PermissionMode.Read */)
}
catch (e: Exception) {
    val cacheDir = File(applicationContext.cacheDir, "com.azuredata.data")
    if (cacheDir.exists) {
        cacheDir.deleteRecursively()
    }

    AzureData.configure(applicationContext, COSMOS_ACCOUNT_NAME, COSMOS_MASTER_KEY, PermissionMode.All /* or PermissionMode.Read */)
}
```

You may also need to delete any shared preferences files that start with the prefix "com.azure.data.lookup", but I'm not sure if that's necessary.

**Comment by SogoGolf** [comment]
hi @bsiegel , thanks for your help with this. actually yes we are using / have enabled "offline" mode. we'll try disabling it as a first step.

**Comment by SogoGolf** [comment]
@bsiegel we removed the offline data flag ```offlineDataEnabled``` and it seems like it might have solved the problem. We're monitoring crash reports and waiting for a few more users to report back before closing, will let you know in next few days.
